"""002_add_signal_logs

Revision ID: 08cd4325aaa8
Revises: afb7ca186578
Create Date: 2026-03-22 15:40:42.089542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08cd4325aaa8'
down_revision: Union[str, None] = 'afb7ca186578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False, comment='rank_jump | new_entry | heat_surge'),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='人类可读的信号描述'),
    sa.Column('value', sa.Float(), nullable=True, comment='信号量化值（如跃升位数、倍数等）'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI 自动分析摘要'),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ai_insights', sa.Column('keyword', sa.String(length=200), nullable=False))
    op.create_index('ix_ai_insights_keyword', 'ai_insights', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_insights_keyword', table_name='ai_insights')
    op.drop_column('ai_insights', 'keyword')
    op.drop_table('signal_logs')
    # ### end Alembic commands ###
