"""001_initial_schema

Revision ID: afb7ca186578
Revises: 
Create Date: 2026-03-19 08:36:07.559331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb7ca186578'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_briefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('matched_keywords', sa.Text(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('notify_email', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('heat_score', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=True),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_insights')
    op.drop_table('trends')
    op.drop_table('keyword_alerts')
    op.drop_table('alert_logs')
    op.drop_table('platforms')
    op.drop_table('keywords')
    op.drop_table('daily_briefs')
    op.drop_table('collector_logs')
    # ### end Alembic commands ###
