"""003_add_trend_relevance_fields

Revision ID: e770506d9786
Revises: 08cd4325aaa8
Create Date: 2026-03-22 16:06:09.075075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e770506d9786'
down_revision: Union[str, None] = '08cd4325aaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('relevance_score', sa.Float(), nullable=True))
    op.add_column('trends', sa.Column('relevance_label', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'relevance_label')
    op.drop_column('trends', 'relevance_score')
    # ### end Alembic commands ###
